GirlsGeek.Solution/GeekGirlsDemo.AppWithoutSPA/Controllers/MagazineController.cs
using System.Web.Mvc;
using GeekGirlsDemo.Business;
using GeekGirlsDemo.Business.Entities;

namespace GeekGirlsDemo.AppWithoutSPA.Controllers
{
    public class MagazineController : Controller
    {
        public ActionResult Index()
        {
            var magazines = BusinessManager.MagazineService.GetMagazinesByYear(2006);
            return View(magazines);
        }

        public ActionResult GetMagazinesByYear(int year)
        {
            var magazines = BusinessManager.MagazineService.GetMagazinesByYear(year);

            return View("Index", magazines);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Magazine());
        }

        [HttpPost]
        public ActionResult Create(Magazine magazine)
        {
            if(!ModelState.IsValid) return View();

            BusinessManager.MagazineService.AddMagazine(magazine);

            return RedirectToAction("Index");
        }

    }
}

GirlsGeek.Solution/GeekGirlsDemo.AppWithoutSPA/Views/Magazine/Create.cshtml
@model GeekGirlsDemo.Business.Entities.Magazine

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 style="color: red;">Create magazine</h2>
<br/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

   
    <div class="form-group">
        <label for="Title">Title</label>
        <input id="Title" type="text" name="Title" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Year">Year</label>
        <input id="Year" type="text" name="Year" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Link">Link</label>
        <input id="Link" type="text" name="Link" class="form-control" />
    </div>


    <input type="submit" value="Save" class="btn btn-success" />

}

<br />
@Html.ActionLink("Back to List", "Index")



GirlsGeek.Solution/GeekGirlsDemo.AppWithoutSPA/Views/Magazine/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model ICollection<GeekGirlsDemo.Business.Entities.Magazine>

@{
    var lastYear = Model.Max(m => m.Year);
}


<h2 style="color:red">Magazines</h2>
<br />
<ul class="nav nav-pills">
    
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2006})">2006</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2007})">2007</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2008})">2008</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2009})">2009</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2010})">2010</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2011})">2011</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2012})">2012</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2013})">2013</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2014})">2014</a></li>
    <li role="presentation"><a href="@Url.RouteUrl(RouteConfig.MagazinesByYearRoute, new {year = 2015})">2015</a></li>
</ul>
<br />
@Html.ActionLink("add new magazine", "Create", "Magazine", new { @class = "btn btn-primary" })
<br />
<br/>

@{
    Html.RenderPartial("MagazineList", Model);
}

GirlsGeek.Solution/GeekGirlsDemo.AppWithoutSPA/Views/Magazine/MagazineList.cshtml
@model ICollection<GeekGirlsDemo.Business.Entities.Magazine>


<table class="table table-hover table-striped table-condensed" style="width: 54%">
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@m.Title</td>
                <td>@m.Year</td>
                <td><a href="@m.Link" target="_blank">Click here</a> for more details</td>
            </tr>
        }
    </tbody>
</table>


GirlsGeek.Solution/GeekGirlsDemo.AppWithoutSPA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GirlsGeekDemo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GirlsGeekDemo Without SPA", "Index", "Magazine", null, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>